sample_table: "config/sample_table.csv"
dir_rawdata: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/data_backups/ont_iso_crc/03_EXON_CRC/"
#ref
file_ref_dna_fa: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/GRCh38/GRCh38_chr.dna.fa"
dbsnp_vcf: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/broad_hg38_v0/Homo_sapiens_assembly38.dbsnp138.vcf"
dbsnp_vcf_index: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/broad_hg38_v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx"
mills_vcf: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/broad_hg38_v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
mills_vcf_index: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/broad_hg38_v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
g1000_vcf: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/broad_hg38_v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
g1000_vcf_index: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/broad_hg38_v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi"
exon_target: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/Sureselect_Human_All_Exon_V7/S31285117_Covered.bed"
common_biallelic_vars: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/somatic_hg38/small_exac_common_3.hg38.vcf.gz"
common_biallelic_vars_index: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/somatic_hg38/small_exac_common_3.hg38.vcf.gz.tbi"
funcotator_db_s: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/funcotator/funcotator_dataSources.v1.7.20200521s"
ref_version: "hg38"
germline_resource: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/somatic_hg38/af-only-gnomad.hg38.vcf.gz"
germline_resource_index: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/somatic_hg38/af-only-gnomad.hg38.vcf.gz.tbi"
common_biallelic_vars: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/somatic_hg38/small_exac_common_3.hg38.vcf.gz"
common_biallelic_vars_index: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/somatic_hg38/small_exac_common_3.hg38.vcf.gz.tbi"

SOFTWARE:
    snpEff: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/software/snpEff/snpEff.jar"
    snpSift: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/software/snpEff/SnpSift.jar"
    snpEff_config: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/software/snpEff/snpEff.config"
    snpSift_db: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/workflow/exon_snv/database/dbNSFP4/hg38/dbNSFP4.1a.txt.gz"
    annovar: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/software/annovar/table_annovar.pl"
    annovar_database: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/software/annovar/humandb"
    annovar_gene_ann: "/gpfs1/tangfuchou_pkuhpc/tangfuchou_cls/luping/software/annovar/example/gene_fullxref.txt"
